"use client";

import { useState, useTransition } from "react";
import { Copy, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { summarizeNote } from "@/lib/ai/actions";
import { Button } from "@/components/ui/button";
import { AIError } from "@/components/ai/ai-error";

export function SummaryTab({
  noteId,
  disabled,
  ensureSaved,
}: {
  noteId: string;
  disabled: boolean;
  ensureSaved: () => Promise<{ ok: true } | { ok: false; error: string }>;
}) {
  const [summary, setSummary] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleGenerate() {
    if (isPending) return; // belt-and-suspenders against a double click racing the transition
    setError(null);
    startTransition(async () => {
      const saveResult = await ensureSaved();
      if (!saveResult.ok) {
        // The note's latest edit hasn't been persisted (or failed to
        // persist) — never let Gemini see a stale or partial version.
        setError(saveResult.error);
        return;
      }
      const result = await summarizeNote(noteId);
      if (result.success) {
        setSummary(result.data.summary);
      } else {
        setError(result.error);
      }
    });
  }

  function handleCopy() {
    if (!summary) return;
    navigator.clipboard.writeText(summary).then(
      () => toast.success("Summary copied."),
      () => toast.error("Couldn't copy to clipboard."),
    );
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between gap-2">
        <p className="text-xs text-muted-foreground">
          A short summary of this note, generated by AI. Nothing is saved until you decide to use it.
        </p>
        <Button
          size="sm"
          variant="secondary"
          onClick={handleGenerate}
          disabled={disabled || isPending}
          className="shrink-0 gap-1.5"
        >
          {isPending ? (
            <Loader2 className="size-3.5 animate-spin" />
          ) : (
            <Sparkles className="size-3.5" />
          )}
          {isPending ? "Generating…" : summary ? "Regenerate" : "Generate summary"}
        </Button>
      </div>

      {error && <AIError message={error} />}

      {summary && !isPending && (
        <div className="rounded-md border bg-secondary/40 p-3">
          <p className="whitespace-pre-wrap text-sm leading-relaxed">{summary}</p>
          <div className="mt-2 flex justify-end">
            <Button size="sm" variant="ghost" onClick={handleCopy} className="h-7 gap-1.5 text-xs">
              <Copy className="size-3.5" />
              Copy
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
